name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: yarn install, build
        run: |
          yarn install
          yarn build

      - name: Generate coverage report
        run: |
          yarn test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/clover.xml
          flags: unittests
          name: codecov-umbrella
